import { ref, computed, watch } from 'vue'
import { darkTheme } from 'naive-ui'
import type { GlobalThemeOverrides } from 'naive-ui'

const isDark = ref(localStorage.getItem('theme') === 'dark')

export function useTheme() {
  watch(isDark, (val) => {
    document.documentElement.setAttribute('data-theme', val ? 'dark' : 'light')
    localStorage.setItem('theme', val ? 'dark' : 'light')
  }, { immediate: true })

  const theme = computed(() => isDark.value ? darkTheme : undefined)

  const themeOverrides = computed<GlobalThemeOverrides>(() => {
    if (isDark.value) {
      return {
        common: {
          primaryColor: '#34D399',
          primaryColorHover: '#6EE7B7',
          primaryColorPressed: '#10B981',
          primaryColorSuppl: '#34D399',
          successColor: '#22C55E',
          successColorHover: '#4ADE80',
          successColorPressed: '#16A34A',
          successColorSuppl: '#22C55E',
          warningColor: '#F59E0B',
          warningColorHover: '#FBBF24',
          warningColorPressed: '#D97706',
          warningColorSuppl: '#F59E0B',
          errorColor: '#EF4444',
          errorColorHover: '#F87171',
          errorColorPressed: '#DC2626',
          errorColorSuppl: '#EF4444',
          infoColor: '#3B82F6',
          infoColorHover: '#60A5FA',
          infoColorPressed: '#2563EB',
          infoColorSuppl: '#3B82F6',
          textColorBase: '#F1F5F9',
          textColor1: '#F1F5F9',
          textColor2: '#94A3B8',
          textColor3: '#475569',
          textColorDisabled: '#334155',
          placeholderColor: '#475569',
          placeholderColorDisabled: '#334155',
          borderColor: '#253348',
          dividerColor: '#253348',
          bodyColor: '#0B1120',
          cardColor: '#141C2E',
          modalColor: '#141C2E',
          popoverColor: '#1A2332',
          tableColor: '#141C2E',
          inputColor: '#1A2332',
          inputColorDisabled: '#141C2E',
          hoverColor: 'rgba(248, 250, 252, 0.05)',
          pressedColor: 'rgba(248, 250, 252, 0.08)',
          fontFamily: "'DM Sans', system-ui, -apple-system, sans-serif",
          fontFamilyMono: "'JetBrains Mono', 'Fira Code', monospace",
          fontSize: '14px',
          fontSizeMedium: '14px',
          fontSizeLarge: '15px',
          borderRadius: '10px',
          borderRadiusSmall: '6px',
          heightMedium: '40px',
          heightLarge: '44px',
          boxShadow1: '0 1px 3px rgba(0, 0, 0, 0.2)',
          boxShadow2: '0 4px 6px rgba(0, 0, 0, 0.25)',
          boxShadow3: '0 10px 15px rgba(0, 0, 0, 0.3)',
        },
        Card: {
          borderRadius: '16px',
          titleFontFamily: "'Space Grotesk', system-ui, -apple-system, sans-serif",
          titleFontSize: '15px',
          titleFontWeight: '600',
          paddingMedium: '20px',
          paddingLarge: '24px',
          color: '#141C2E',
          colorModal: '#141C2E',
          borderColor: '#1E2A3A',
        },
        Menu: {
          itemTextColor: '#94A3B8',
          itemTextColorActive: '#F1F5F9',
          itemTextColorActiveHover: '#F1F5F9',
          itemTextColorChildActive: '#F1F5F9',
          itemTextColorHover: '#CBD5E1',
          itemIconColor: '#64748B',
          itemIconColorActive: '#34D399',
          itemIconColorActiveHover: '#34D399',
          itemIconColorHover: '#94A3B8',
          itemColorActive: 'rgba(52, 211, 153, 0.10)',
          itemColorHover: 'rgba(248, 250, 252, 0.04)',
          borderRadius: '10px',
          itemHeight: '42px',
        },
        Button: {
          borderRadiusMedium: '10px',
          borderRadiusSmall: '8px',
          borderRadiusLarge: '12px',
          fontWeight: '500',
          heightMedium: '36px',
          fontSizeMedium: '14px',
          colorPrimary: '#34D399',
          colorHoverPrimary: '#6EE7B7',
          colorPressedPrimary: '#10B981',
          colorFocusPrimary: '#34D399',
          textColorPrimary: '#0B1120',
          textColorHoverPrimary: '#0B1120',
          textColorPressedPrimary: '#0B1120',
          textColorFocusPrimary: '#0B1120',
        },
        DataTable: {
          thColor: '#1A2332',
          thTextColor: '#94A3B8',
          thFontWeight: '600',
          borderRadius: '12px',
          borderColor: '#1E2A3A',
          tdColor: '#141C2E',
          tdColorHover: 'rgba(52, 211, 153, 0.04)',
        },
        Input: {
          borderRadius: '10px',
          placeholderColor: '#475569',
          color: '#1A2332',
          borderColor: '#1E2A3A',
          borderHover: '#2A3A4E',
          borderFocus: '#34D399',
          boxShadowFocus: '0 0 0 2px rgba(52, 211, 153, 0.15)',
          caretColor: '#34D399',
        },
        Tag: {
          borderRadius: '8px',
        },
        Statistic: {
          labelFontFamily: "'DM Sans', system-ui, -apple-system, sans-serif",
          labelTextColor: '#94A3B8',
          valueFontFamily: "'Space Grotesk', system-ui, -apple-system, sans-serif",
          valueFontSize: '28px',
          valueFontWeight: '700',
          valueTextColor: '#F1F5F9',
        },
        Layout: {
          borderColor: '#1E2A3A',
          siderColor: '#0D1525',
          headerColor: '#141C2E',
        },
        Modal: {
          borderRadius: '16px',
          color: '#141C2E',
        },
        Form: {
          labelTextColor: '#94A3B8',
          feedbackTextColor: '#475569',
        },
        Select: {
          peers: {
            InternalSelection: {
              borderRadius: '10px',
              borderHover: '#2A3A4E',
              borderFocus: '#34D399',
              boxShadowFocus: '0 0 0 2px rgba(52, 211, 153, 0.15)',
            },
          },
        },
        Badge: {
          color: '#34D399',
        },
        Skeleton: {
          color: '#1A2332',
          colorEnd: '#1E2A3A',
        },
      }
    }

    return {
      common: {
        primaryColor: '#22C55E',
        primaryColorHover: '#16A34A',
        primaryColorPressed: '#15803D',
        primaryColorSuppl: '#22C55E',
        successColor: '#22C55E',
        successColorHover: '#16A34A',
        successColorPressed: '#15803D',
        successColorSuppl: '#22C55E',
        warningColor: '#F59E0B',
        warningColorHover: '#D97706',
        warningColorPressed: '#B45309',
        warningColorSuppl: '#F59E0B',
        errorColor: '#EF4444',
        errorColorHover: '#DC2626',
        errorColorPressed: '#B91C1C',
        errorColorSuppl: '#EF4444',
        infoColor: '#3B82F6',
        infoColorHover: '#2563EB',
        infoColorPressed: '#1D4ED8',
        infoColorSuppl: '#3B82F6',
        textColorBase: '#1E293B',
        textColor1: '#1E293B',
        textColor2: '#475569',
        textColor3: '#94A3B8',
        textColorDisabled: '#CBD5E1',
        placeholderColor: '#94A3B8',
        placeholderColorDisabled: '#CBD5E1',
        borderColor: '#E2E8F0',
        dividerColor: '#E2E8F0',
        bodyColor: '#F8FAFC',
        cardColor: '#FFFFFF',
        modalColor: '#FFFFFF',
        popoverColor: '#FFFFFF',
        tableColor: '#FFFFFF',
        inputColor: '#FFFFFF',
        inputColorDisabled: '#F1F5F9',
        hoverColor: 'rgba(30, 41, 59, 0.04)',
        pressedColor: 'rgba(30, 41, 59, 0.08)',
        fontFamily: "'DM Sans', system-ui, -apple-system, sans-serif",
        fontFamilyMono: "'JetBrains Mono', 'Fira Code', monospace",
        fontSize: '14px',
        fontSizeMedium: '14px',
        fontSizeLarge: '15px',
        borderRadius: '10px',
        borderRadiusSmall: '6px',
        heightMedium: '40px',
        heightLarge: '44px',
        boxShadow1: '0 1px 2px rgba(0, 0, 0, 0.04)',
        boxShadow2: '0 4px 6px rgba(0, 0, 0, 0.06)',
        boxShadow3: '0 10px 15px rgba(0, 0, 0, 0.08)',
      },
      Card: {
        borderRadius: '16px',
        titleFontFamily: "'Space Grotesk', system-ui, -apple-system, sans-serif",
        titleFontSize: '15px',
        titleFontWeight: '600',
        paddingMedium: '20px',
        paddingLarge: '24px',
      },
      Menu: {
        itemTextColor: '#64748B',
        itemTextColorActive: '#1E293B',
        itemTextColorActiveHover: '#1E293B',
        itemTextColorChildActive: '#1E293B',
        itemTextColorHover: '#334155',
        itemIconColor: '#64748B',
        itemIconColorActive: '#22C55E',
        itemIconColorActiveHover: '#22C55E',
        itemIconColorHover: '#475569',
        itemColorActive: 'rgba(34, 197, 94, 0.08)',
        itemColorHover: 'rgba(30, 41, 59, 0.04)',
        borderRadius: '10px',
        itemHeight: '42px',
      },
      Button: {
        borderRadiusMedium: '10px',
        borderRadiusSmall: '8px',
        borderRadiusLarge: '12px',
        fontWeight: '500',
        heightMedium: '36px',
        fontSizeMedium: '14px',
        colorPrimary: '#22C55E',
        colorHoverPrimary: '#16A34A',
        colorPressedPrimary: '#15803D',
        colorFocusPrimary: '#22C55E',
        textColorPrimary: '#FFFFFF',
        textColorHoverPrimary: '#FFFFFF',
        textColorPressedPrimary: '#FFFFFF',
        textColorFocusPrimary: '#FFFFFF',
      },
      DataTable: {
        thColor: '#F8FAFC',
        thTextColor: '#64748B',
        thFontWeight: '600',
        borderRadius: '12px',
        borderColor: '#E2E8F0',
        tdColor: '#FFFFFF',
        tdColorHover: 'rgba(34, 197, 94, 0.03)',
      },
      Input: {
        borderRadius: '10px',
        placeholderColor: '#94A3B8',
        borderHover: '#CBD5E1',
        borderFocus: '#22C55E',
        boxShadowFocus: '0 0 0 2px rgba(34, 197, 94, 0.12)',
        caretColor: '#22C55E',
      },
      Tag: {
        borderRadius: '8px',
      },
      Statistic: {
        labelFontFamily: "'DM Sans', system-ui, -apple-system, sans-serif",
        labelTextColor: '#64748B',
        valueFontFamily: "'Space Grotesk', system-ui, -apple-system, sans-serif",
        valueFontSize: '28px',
        valueFontWeight: '700',
        valueTextColor: '#1E293B',
      },
      Layout: {
        borderColor: '#E2E8F0',
      },
      Modal: {
        borderRadius: '16px',
      },
      Form: {
        labelTextColor: '#475569',
        feedbackTextColor: '#94A3B8',
      },
      Select: {
        peers: {
          InternalSelection: {
            borderRadius: '10px',
            borderHover: '#CBD5E1',
            borderFocus: '#22C55E',
            boxShadowFocus: '0 0 0 2px rgba(34, 197, 94, 0.12)',
          },
        },
      },
      Badge: {
        color: '#22C55E',
      },
    }
  })

  function toggleTheme() {
    isDark.value = !isDark.value
  }

  return { isDark, theme, themeOverrides, toggleTheme }
}
